# Generated by Django 5.0.1 on 2024-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
