# Generated by Django 5.0.1 on 2024-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='guest',
            field=models.IntegerField(default=0),
        ),
    ]
