# Generated by Django 5.0.1 on 2024-09-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_experience_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecategory',
            name='name',
            field=models.CharField(choices=[('adventure_outdoor', 'Adventure & Outdoor'), ('cultural_historical', 'Cultural & Historical'), ('food_drink', 'Food & Drink'), ('wellness_relaxation', 'Wellness & Relaxation'), ('entertainment_shows', 'Entertainment & Shows'), ('workshops_learning', 'Workshops & Learning'), ('nature_wildlife', 'Nature & Wildlife'), ('water_activities', 'Water Activities'), ('romantic_special', 'Romantic & Special Occasions'), ('family_friendly', 'Family-Friendly'), ('luxury_experiences', 'Luxury Experiences'), ('seasonal_holiday', 'Seasonal & Holiday')], max_length=50),
        ),
    ]
