# Generated by Django 5.0.1 on 2024-10-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_vendorpaypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='paypal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vendorpaypal'),
        ),
    ]
