# Generated by Django 5.0.1 on 2024-10-06 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_chatmessage_experience_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='base.experience'),
        ),
    ]
