# Generated by Django 5.0.1 on 2024-10-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_transaction_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='vendor_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
        ),
    ]
