# Generated by Django 5.0.1 on 2024-10-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_customuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='paypal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vendorpaypal'),
        ),
    ]
