# Generated by Django 5.0.1 on 2024-10-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='calendar_view',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='price_per_guest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='private_group_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='sessions_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
