# Generated by Django 5.0.1 on 2024-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_experience_calendar_view_experience_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='max_guests',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='min_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
