# Generated by Django 5.0.1 on 2024-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_experience_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
