# Generated by Django 5.0.1 on 2024-10-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_private_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpaypal',
            old_name='paypal_email',
            new_name='Razor_account_id',
        ),
    ]
