# Generated by Django 5.0.1 on 2024-10-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_paypal_email_vendorpaypal_razor_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='extra_services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='private_group_max_guests',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='experience',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='experience_videos/'),
        ),
    ]
