# Generated by Django 5.0.1 on 2024-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_experience_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='paypal',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
